name := "mcmc"
version := "0.1"
organization := "org.compevol"
scalaVersion := "2.12.1"
libraryDependencies += "org.spire-math" %% "spire" % "0.13.0"
libraryDependencies += "com.github.julien-truffaut" %% "monocle-core" % "1.4.0-M2"
